package com.zcbspay.platform.payment.trade.route.pojo;
// default package
// Generated 2017-3-17 9:38:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TMerchBankAccount generated by hbm2java
 */
@Entity
@Table(name = "T_MERCH_BANK_ACCOUNT")
public class MerchBankAccountDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -8580829502508544945L;
	private long tid;
	private String merchno;
	private String banknode;
	private String bankcode;
	private String accountno;
	private String accountname;
	private String protocoltype;
	private String bankprovince;
	private String bankcity;
	private String channelcode;
	private String status;
	private String notes;
	private String remarks;

	public MerchBankAccountDO() {
	}

	public MerchBankAccountDO(long tid, String accountname) {
		this.tid = tid;
		this.accountname = accountname;
	}

	public MerchBankAccountDO(long tid, String merchno, String banknode,
			String bankcode, String accountno, String accountname,
			String protocoltype, String bankprovince, String bankcity,
			String channelcode, String status, String notes, String remarks) {
		this.tid = tid;
		this.merchno = merchno;
		this.banknode = banknode;
		this.bankcode = bankcode;
		this.accountno = accountno;
		this.accountname = accountname;
		this.protocoltype = protocoltype;
		this.bankprovince = bankprovince;
		this.bankcity = bankcity;
		this.channelcode = channelcode;
		this.status = status;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "MERCHNO", length = 15)
	public String getMerchno() {
		return this.merchno;
	}

	public void setMerchno(String merchno) {
		this.merchno = merchno;
	}

	@Column(name = "BANKNODE", length = 14)
	public String getBanknode() {
		return this.banknode;
	}

	public void setBanknode(String banknode) {
		this.banknode = banknode;
	}

	@Column(name = "BANKCODE", length = 14)
	public String getBankcode() {
		return this.bankcode;
	}

	public void setBankcode(String bankcode) {
		this.bankcode = bankcode;
	}

	@Column(name = "ACCOUNTNO", length = 32)
	public String getAccountno() {
		return this.accountno;
	}

	public void setAccountno(String accountno) {
		this.accountno = accountno;
	}

	@Column(name = "ACCOUNTNAME", nullable = false, length = 64)
	public String getAccountname() {
		return this.accountname;
	}

	public void setAccountname(String accountname) {
		this.accountname = accountname;
	}

	@Column(name = "PROTOCOLTYPE", length = 2)
	public String getProtocoltype() {
		return this.protocoltype;
	}

	public void setProtocoltype(String protocoltype) {
		this.protocoltype = protocoltype;
	}

	@Column(name = "BANKPROVINCE", length = 10)
	public String getBankprovince() {
		return this.bankprovince;
	}

	public void setBankprovince(String bankprovince) {
		this.bankprovince = bankprovince;
	}

	@Column(name = "BANKCITY", length = 4)
	public String getBankcity() {
		return this.bankcity;
	}

	public void setBankcity(String bankcity) {
		this.bankcity = bankcity;
	}

	@Column(name = "CHANNELCODE", length = 8)
	public String getChannelcode() {
		return this.channelcode;
	}

	public void setChannelcode(String channelcode) {
		this.channelcode = channelcode;
	}

	@Column(name = "STATUS", length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "NOTES", length = 128)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 128)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
